# Generated by Django 4.2.4 on 2023-08-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_likes_post_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
