# Generated by Django 4.2.4 on 2023-08-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
